### PR TITLE
enable server.basePath configuration

### PR DESCRIPTION
**Pull request by astik**
Being able to configure server.basePath would allow us to have an Nginx reverse proxy with kibana mount on something else than the root. By default, kibana redirect root access to /app/kibana.

With Nginx, we can have a configuration like this :

```
upstream kibana_upstream {
    server 127.0.0.1:5601;
    keepalive 64;
}
location /secured/search/ {
    rewrite ^/secured/search/(.*) /$1 break;
    proxy_pass   http://kibana_upstream;
}
```

Then we can access kibana through Nginx, http://MY-HOST/secured/search, then kibana will redirect to : http://MY-HOST/secured/search/app/kibana.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Please rebase, and make this variable an optional variable, by adding an `if` condition around it in the config file, as mentioned in https://github.com/geerlingguy/ansible-role-kibana/pull/16#issuecomment-425301328

Will definitely merge once the variable is documented in README, and there's an if around it in the config file. Thanks!

**Comment by ndejong** [comment]
This is a worthy PR however the CI is failing because the functionality of this PR is to change the base URL which hence causes the test-defined-with-molecule to fail because the URL `http://127.0.0.1:5601/login` is hard-coded into the `playbook.yml` without an ability to introduce a path.

Without knowing how to pass a variable from Ansible to Molecule resolving this CI issue is not clear, perhaps @geerlingguy could suggest something that correctly achieves the intent of the below (non-working) Molecule `playbook.yml` - it's all about how to pass `kibana_server_basepath` through from Ansible to Molecule.

```
  post_tasks:

    - name: Ensure Kibana is running (no kibana_server_basepath value).
      uri:
        url: http://127.0.0.1:5601/login
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      when: kibana_server_basepath is not defined or kibana_server_basepath == ''

    - name: Ensure Kibana is running (with kibana_server_basepath set).
      uri:
        url: http://127.0.0.1:5601/{{ kibana_server_basepath }}/login
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      when: kibana_server_basepath is defined and kibana_server_basepath != ''
```

**Comment by astik** [comment]
@ndejong the CI failure is not relative to this PR, the problem is the same on the master branch.

**Comment by astik** [comment]
Hi @geerlingguy, i just rebased the code. With all the changes you made on the CI, this PR is now checked correctly.
Are all the modifications you were expected good enough ?

**Comment by astik** [comment]
This feature is still needed =D

**Comment by astik** [comment]
A bad rebase led to this PR being closed, sorry ... a new PR has been opened : #56

**Pull request closed without merging**
