### PR TITLE
Kibana 5.x option

### PR DESCRIPTION
**Pull request by juju4**
follow elastic, logstash 5.x

### CODE REVIEW

**Comment by juju4** [comment]
feedback? thanks

**Comment by drakkhen** [comment]
Thank you for this 👍

**Comment by drakkhen** [comment]
@geerlingguy Can we get this merged in?

**Comment by geerlingguy** [comment]
There are a few things I would need to do / have someone do before I could merge in 5.x support:

  - Has to be on CentOS/Red Hat as well
  - Needs to have a test that demonstrates 4.x vs 5.x installation
  - Service template should be version-specific (e.g. instead of having one template with if/else on version, have one template for < 5, and another for 5, and switch via the `include` in the main task file).

There are a few other things (like the `set_fact` tasks) which I think could be cleaned up or made to be more readable.

**Comment by juju4** [comment]
* centos support was already there
* test. had a kitchen one. pushed one inside travis. I kept the old format as your new wget script doesn't allow me to add tests.
* I suppose that you are talking about repo template as there is no service template. done
* set_fact move to vars/
* merged with upstream

Some tests were failing on older distribution because acl module is not idempotent for them.
so moved to chown on directory only.

**Comment by Lusitaniae** [comment]
@geerlingguy, is there something else missing before this can be merged?

**Comment by Thalience** [comment]
@juju4 Thanks for this! I've merged this into the fork I'm using at work.

**Comment by secfigo** [comment]
@geerlingguy can we get this merged ?

**Comment by hypery2k** [comment]
@geerlingguy Would be great to merge this

**Comment by geerlingguy** [comment]
_Sorry about the delays in getting to this role's PRs this year!_

I just published role version 3.0.0, which defaults to Kibana version `6.x`, and has everything updated for both Debian and RedHat derivatives to work with the latest version.

I also added a new variable, `kibana_config_template`, which allows playbooks to override the simple template included with this role for more advanced use cases.

Finally, there are now configuration options for controlling whether the `kibana` service is started and/or enabled for boot (so you can control kibana installs with this role more easily in places like containers where a service manager wouldn't be present).

I _think_ this setup should also work fine with 5.x, if you want to stick with that slightly older version. Just change the `kibana_version` to `5.x` instead of the default `6.x`.

**Pull request closed without merging**
